[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:mysql]
command=docker-entrypoint.sh mysqld --bind-address=0.0.0.0
priority=10
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=5
stopasgroup=true
killasgroup=true

[program:knowledge]
command=/app/scripts/run-app.sh
priority=20
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=5
stopasgroup=true
killasgroup=true
