# 在宿主机启动 Java 后端并测试 SSE 的辅助脚本
$env:MYSQL_URL="jdbc:mysql://localhost:3306/knowledge_rag?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8"
$env:MYSQL_USERNAME="knowledge"
$env:MYSQL_PASSWORD="zphhpzzph"
$env:LLM_CHAT_PROVIDER="vllm"
$env:LLM_EMBEDDING_PROVIDER="vllm"
$env:LLM_TIMEOUT="12000s"
$env:VLLM_CHAT_BASE_URL="http://222.200.112.60/v1"
$env:VLLM_EMBEDDING_BASE_URL="http://222.200.112.60/v1"
$env:VLLM_CHAT_MODEL="glm-4.6v-flash"
$env:VLLM_EMBEDDING_MODEL="qwen3-embedding-4b"
$env:VLLM_CHAT_API_KEY="sk-shiliuziyyds"
$env:VLLM_EMBEDDING_API_KEY="sk-shiliuziyyds"
$env:VLLM_RETURN_THINKING="true"
$env:QDRANT_HOST="localhost"
$env:QDRANT_PORT="6334"
$env:QDRANT_HTTP_PORT="6333"
$env:QDRANT_VECTOR_SIZE="2560"
$env:QDRANT_CREATE_COLLECTION_IF_NOT_EXISTS="true"
$env:LOG_LEVEL_ROOT="INFO"
$env:LOG_LEVEL_APP="DEBUG"
$env:LOG_LEVEL_LANGCHAIN4J="DEBUG"

& ./mvnw spring-boot:run
